"""empty message

Revision ID: 625bec2e5cc4
Revises: 
Create Date: 2022-03-17 23:46:13.100490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '625bec2e5cc4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('property_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_title', sa.String(length=150), nullable=True),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('no_of_bedrooms', sa.String(length=80), nullable=True),
    sa.Column('no_of_bathrooms', sa.String(length=80), nullable=True),
    sa.Column('price', sa.String(length=80), nullable=True),
    sa.Column('property_type', sa.String(length=50), nullable=True),
    sa.Column('loc', sa.String(length=100), nullable=True),
    sa.Column('photo_name', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('property_info')
    # ### end Alembic commands ###
